name: Update Brand Products (Manual)

on:
  workflow_dispatch:
    inputs:
      brand:
        description: 'Enter brand name (e.g., amul, parle)'
        required: true
        default: 'amul'

jobs:
  update-brand:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install pandas requests

      - name: Run update script
        run: |
          python scripts/update_brand_products.py "${{ github.event.inputs.brand }}"

      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add Brands/*.csv README.md
          git commit -m "🔄 Auto-update for ${{ github.event.inputs.brand }} on $(date -u +'%Y-%m-%d')" || echo "No changes to commit"
          git push
